homeassistant:
  name: Home
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam
  latitude: !secret wolfstein_latitude 
  longitude: !secret wolfstein_longitude 
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.13.0/24
        - 127.0.0.1

# Enables the frontend
frontend:

# Enables configuration UI
discovery:

api:
  api_password: !secret http_password
  api_port: 8123

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  base_url: ns.wolfstein.nl:8123
  server_port: 8123


tplink: 
  discovery: true
  switch: 
    - host: 192.168.13.241
    - host: 192.168.13.242
    - host: 192.168.13.243
    - host: 192.168.13.244

switch:
  platform: revogi
  host: 192.168.13.240
  name: stekkerdoos

