homeassistant:
  name: Home
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam
  latitude: !secret wolfstein_latitude 
  longitude: !secret wolfstein_longitude 
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.13.0/24
        - 127.0.0.1

# Enables the frontend
frontend:

# Enables configuration UI
discovery:

# Checks for available updates
updater:

#lovelace: 
#  mode: yaml


logger:
  default: info
  logs: 
    homeassistant.core: debug




recorder:
  purge_keep_days: 5

# Enables support for tracking state changes over time.
history:

influxdb:
  host: 192.168.13.1
  database: thuis
  username: !secret influxdb_user
  password: !secret influxdb_pass
# View all events in a logbook
logbook:

api:
  api_password: !secret http_password
  api_port: 8123

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  base_url: (!secret wolfstein_url):8123
  server_port: 8123


tplink: 
  discovery: true
  switch: 
    - host: 192.168.13.241
    - host: 192.168.13.242
    - host: 192.168.13.243
    - host: 192.168.13.244

switch:
  platform: revogi
  host: 192.168.13.240
  name: stekkerdoos


input_datetime:
  both_date_and_time:
    name: Input with both date and time
    has_date: true
    has_time: true
  only_date:
    name: Input with only date
    has_date: true
    has_time: false
  only_time:
    name: Input with only time
    has_date: false
    has_time: true

automation: 
  - alias: "turn off tv in bedroom"
    trigger: 
      platform: time
      at: '9:00:00' 
    action: 
      service: homeassistant.turn_off
      entity_id: switch.slaapkamer
  
  - alias: "turn on tv in living"
    trigger: 
        platform: time
        at: '6:45:00' 
    action: 
        service: homeassistant.turn_on
        entity_id: switch.reciever

binary_sensor:
  - platform: ping
    host: meetstation.wolfstein.nl
    name: meetstation
    count: 2
    scan_interval: 30 
remote: 
  - platform: harmony
    name: harmony
    host: 192.168.13.248
