title: My Awesome Home
views:
  - title: Beneden
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: glance
        title: beneden
        show_state: true
        entities:    
          -  entity: switch.office
             name: kantoor
             icon: mdi:cellphone-link
             tap_action: 
               action: toggle
             hold_action:
               action: more-info 
          -  entity: switch.stekkerdoos5
             name: playstation
             tap_action: 
               action: toggle
             hold_action:
               action: more-info 
          -  entity: group.watch_tv
             name: "tv kijken" 
             icon: mdi:television
             tap_action: 
               action: toggle
             hold_action:
               action: more-info 
          -  entity: switch.poe
             name: "wired network" 
             icon: mdi:server-network
             tap_action: 
               action: toggle
             hold_action:
               action: more-info 


  - title: boven
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: glance    
        title: boven
        show_state: true
        entities:    
        -  entity: switch.poe
           name: "wifi"
           icon: mdi:wifi
           tap_action: 
             action: toggle
           hold_action:
             action: more-info 
        -  entity: switch.slaapkamer
           name: "slaapkamer TV"
           icon: mdi:television-guide
           tap_action: 
             action: toggle
           hold_action:
             action: more-info 

 
  - title: boven2
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    type: horizontal-stack
    cards:
    - type: glance 
      entities:
        -  entity: switch.poe
           name: "wifi"
           icon: mdi:wifi
           tap_action: 
             action: toggle
           hold_action:
             action: more-info 
    cards:
    - type: glance 
      entities:
        -  entity: switch.slaapkamer
           name: "slaapkamer TV"
           icon: mdi:television-guide
           tap_action: 
             action: toggle
           hold_action:
