title: My Awesome Home
views:
  - title: Example
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
      
      - type: glance
        title: beneden
        show_state: true
        entities:    
          -  entity: switch.office
             name: kantoor
             # icon: mdi:cellphone-link
             state_icon:
               "on": mdi:cellphone-link
               "off": mdi:cellphone-link-off
             tap_action: 
               action: toggle
             hold_action:
               action: more-info 
          -  entity: switch.stekkerdoos5
             name: playstation
             tap_action: 
               action: toggle
             hold_action:
               action: more-info 
          -  entity: group.watch_tv
             name: "tv kijken" 
             icon: mdi:television
             tap_action: 
               action: toggle
             hold_action:
               action: more-info 


# tap_action: 
#          action: toggle
#          entity: switch.turn_off
#      entity: switch.poe
